### ISSUE TITLE
I'd like to input a blank line by pressing the 'Enter' key into the log field.

### ISSUE THREAD

**Issue by seak0503** [sarub0b0/kubetui#312]
It would be great if I into a blank line into the log field.

As I tried to test my apps many times, I sometimes couldn't find the test log. 
What if I could input a blank line into the log field by pressing the 'Enter'?
I'm sure I can find the log I want to see fast because blank line becomes a landmark.

Please think on it.

**Comment by sarub0b0** [comment]
@seak0503 Thank you for creating issue and sharing your great idea. I'd love to add it to the kubetui.

**Comment by seak0503** [comment]
@sarub0b0 

Thanks for your new release.
It's very kind of you to support.
