### ISSUE TITLE
Feature Request: base64 decoding of Raw Data

### ISSUE THREAD

**Issue by Lockszmith-GH** [sarub0b0/kubetui#425]
Absolutley fabulous application.

I started with writing a script for myself that would dump multiple facets from kubectl.
Then I thought, somebody probably have thought about it already, and searching GitHub, your project came up.
What an absolute delight!!

So I want to start with a most sincere THANK YOU.

As for my feature request:
Helm charts are preserved as base64 encoded secrets on my cluster. I would love to have a base64 encoding toggle when viewing these.

**Comment by sarub0b0** [comment]
Thanks a bunch for the glowing feedback on my app!  I am stoked that you found it helpful.

Regarding your feature request, I love the idea and plan to add it to the app. I'm currently occupied with other features, so please bear with me. It might take a bit, but I am committed to making it happen.

**Comment by sarub0b0** [comment]
@Lockszmith-GH 
Thanks a bunch for the glowing feedback on my app! I am stoked that you found it helpful.

Regarding your feature request, I love the idea and plan to add it to the app. I'm currently occupied with other features, so please bear with me. It might take a bit, but I am committed to making it happen.

**Comment by sarub0b0** [comment]
memo

[Decoding Helm3 resources in secrets](https://gist.github.com/DzeryCZ/c4adf39d4a1a99ae6e594a183628eaee)

**Comment by sarub0b0** [comment]
@Lockszmith-GH 

I have made changes to display both the encoded `release` object and the decoded `release (decoded)` object. If you prefer a different approach or have any specific requirements, please let me know.

**Comment by Lockszmith-GH** [comment]
I literally checked whether there is a new release, about an hour before your reply here.
This would be awesome, can't wait to test it out. Can't run rust on the machine I'm testing it though, so I'll wait for a release binary.

**Comment by sarub0b0** [comment]
Thank you for your patience. I have released a new binary. Please give it a try!

**Comment by Lockszmith-GH** [comment]
Amazing! This really awesome.

**Comment by sarub0b0** [comment]
There don't seem to be any particular issues, so I will close this.
If you have any further questions or concerns, please feel free to reach out.

**Comment by Lockszmith-GH** [comment]
I never posted back (sorry about that).
I've been using this for at least a month now, and this is invaluable in trobleshooting.

Thank you so much for the update. `kubetui` is an invaluable tool for me working with TrueNAS SCALE, as it provides the insight I need when troubleshooting.
